"""
Recorded test: darkmode
"""


def run(h):
    h.screenshot("01_initial")
    h.wait(3.0)
    h.click(578, 563, button=1)
    h.screenshot("02_click_578_563")
    h.wait(1.15)
    h.key("Down")
    h.screenshot("03_Down")
    h.wait(0.53)
    h.key("Up")
    h.screenshot("04_Up")
    h.wait(0.75)
    h.key("Return")
    h.screenshot("05_Return")
    h.wait(0.73)
    h.wait(0.3)
    h.type("I")
    h.key("space")
    h.screenshot("06_space")
    h.wait(0.27)
    h.wait(0.16)
    h.wait(0.16)
    h.screenshot("07_step")
    h.screenshot("08_step")
    h.wait(0.6)
    h.type("sure")
    h.key("Return")
    h.screenshot("09_Return")
    h.screenshot("10_step")
    h.wait(3.0)
    h.key("Down")
    h.wait(0.37)
    h.key("Down")
    h.screenshot("11_Down")
    h.wait(0.36)
    h.key("Up")
    h.screenshot("12_Up")
    h.wait(0.26)
    h.key("Up")
    h.screenshot("13_Up")
    h.wait(0.59)
    h.key("Escape")
    h.screenshot("14_Escape")
    h.screenshot("15_step")
    h.wait(0.75)
    h.key("Escape")
