"""
Recorded test: macsimple
"""


def run(h):
    h.screenshot("01_initial")
    h.wait(0.6)
    h.key("Down")
    h.wait(0.31)
    h.key("Down")
    h.screenshot("02_Down")
    h.wait(0.31)
    h.key("Down")
    h.screenshot("03_Down")
    h.wait(0.3)
    h.key("Down")
    h.wait(0.33)
    h.key("Return")
    h.screenshot("04_Return")
    h.screenshot("05_step")
    h.wait(0.69)
    h.key("Escape")
    h.screenshot("06_Escape")
    h.wait(0.95)
    h.wait(0.18)
    h.type("ski")
    h.key("space")
    h.screenshot("07_space")
    h.wait(0.17)
    h.wait(0.19)
    h.screenshot("08_step")
    h.screenshot("09_step")
    h.wait(0.23)
    h.type("chicken")
    h.key("Return")
    h.screenshot("10_Return")
    h.screenshot("11_step")
    h.wait(3.0)
    h.key("Escape")
    h.screenshot("12_Escape")
    h.wait(0.52)
    h.key("Escape")
