"""
Recorded test: banner
"""


def run(h):
    h.screenshot("01_initial")
    h.wait(2.31)
    h.click(165, 473, button=1)
    h.screenshot("02_click_165_473")
    h.wait(3.0)
    h.mousedown(190, 475, button=3)
    h.screenshot("03_step", stable=False)
    h.wait(0.44)
    h.mouseup(190, 475, button=3)
    h.wait(0.67)
    h.click(236, 510, button=1)
    h.screenshot("04_click_236_510")
    h.wait(1.69)
    h.click(439, 473, button=1)
    h.screenshot("05_click_439_473")
    h.wait(3.0)
    h.key("Down")
    h.screenshot("06_Down")
    h.wait(1.18)
    h.key("Down")
    h.screenshot("07_Down")
    h.wait(0.77)
    h.key("Return")
    h.screenshot("08_Return")
    h.wait(0.95)
    h.key("Return")
    h.screenshot("09_Return")
    h.wait(0.65)
    h.key("Down")
    h.screenshot("10_Down")
    h.wait(0.66)
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.screenshot("11_Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.key("Down")
    h.screenshot("12_Down")
    h.key("Down")
    h.key("Down")
    h.wait(0.36)
    h.key("Return")
    h.screenshot("13_Down")
    h.screenshot("14_step")
    h.wait(2.8)
    h.key("Down")
    h.key("Down")
    h.screenshot("15_Down")
    h.wait(0.35)
    h.key("Return")
